### ISSUE TITLE
Documentation, react and other help

### ISSUE THREAD

**Issue by MaTeMaTuK** [bignumlock/react-gantt-elastic#5]
Hi @bignumlock ,
You did a great job, but there's a lot left. Can I help you somehow?

**Comment by bignumlock** [comment]
It's a great honor to see and follow this project. Your participation will make this project even better.

**Comment by MaTeMaTuK** [comment]
Good, But How I can help you?

**Comment by bignumlock** [comment]
Yes! I don't know much about GitHub's project management methods, but I have added you to the list of collaborators.

**Comment by MaTeMaTuK** [comment]
Could you please send me an email? My Mail: battakycyku@gmail.com

**Comment by bignumlock** [comment]
I added you to the collaborator list yesterday, with the name @MaTeMaTuK. But it has been waiting [Awaiting MaTeMaTuK ’s response], I do n’t understand why.
